# frozen_string_literal: true

# Released under the MIT License.
# Copyright, 2025-2026, by Samuel Williams.
# Copyright, 2025, by Shopify Inc.

require "fileutils"
require "pathname"
require "yaml"
require "uri"
require "tempfile"
require "rubygems"
require "agent/context/skills/ownership"
require "agent/context/skills/exclusion"
require_relative "paths"
require_relative "document"

module Agent
	module Context
		# Represents the generated index of installed dependency guidance.
		class Index
			# Initialize an index for installed context.
			# @parameter context_path [String] The installed context directory.
			# @parameter specifications [Enumerable] The resolved gems supplying package descriptions.
			def initialize(context_path = CONTEXT_PATH, specifications: ::Gem::Specification)
				@context_path = File.expand_path(context_path)
				@package_descriptions = specifications.to_a.to_h{|specification| [specification.name, specification.summary]}
			end
			
			# @attribute [String] The installed context directory.
			attr_reader :context_path
			
			# Write the generated index and update local Git exclusions.
			def update_index
				content = generate_index
				FileUtils.mkdir_p(@context_path)
				Tempfile.create(".agent-context-index-", @context_path) do |file|
					file.write(content)
					file.flush
					File.rename(file.path, File.join(@context_path, "index.md"))
				end
				root = File.dirname(File.dirname(@context_path))
				owners = Skills::Ownership.scan(File.join(root, ".agents", "skills"))
				Skills::Exclusion.prepare(root, owners.keys)&.apply
			end
			
			# Render links relative to the generated index, preserving custom provider metadata.
			# @returns [String] The generated Markdown index.
			def generate_index
				sections = [
					"# Context Index", "",
					"This index links to guidance installed from resolved gem dependencies. It is generated by `bake agent:context:install` and can be refreshed with `bake agent:context:index`.", "",
					"Before working on a package, read the relevant context files below. If these files are missing, run `bake agent:context:install`.", "",
				]
				providers = Dir.exist?(@context_path) ? Dir.children(@context_path).sort.select{|name| File.directory?(File.join(@context_path, name)) && !File.symlink?(File.join(@context_path, name))} : []
				found = false
				providers.each do |name|
					directory = File.join(@context_path, name)
					files = Dir.glob(File.join(directory, "**", "*")).select{|path| File.file?(path) && !File.symlink?(path) && File.extname(path).downcase == ".md"}
					documents = {}
					skill_roots = []
					files.sort_by{|path| [File.dirname(path) == directory ? 0 : 1, path]}.each do |path|
						relative = Pathname.new(path).relative_path_from(Pathname.new(directory)).to_s
						next if skill_roots.any?{|skill| relative.start_with?("#{skill}/")}
						document = Document.new(path)
						if document.skill?
							skill_roots << relative.delete_suffix(File.extname(relative))
						else
							documents[relative] = document
						end
					end
					next if documents.empty?
					found = true
					metadata = load_gem_index(directory)
					sections.concat(["## #{escape(name)}", "", escape(metadata["description"] || @package_descriptions[name] || "Context files for #{name}"), ""])
					listed = []
					Array(metadata["files"]).each do |entry|
						next unless entry.is_a?(Hash) && documents.key?(entry["path"]) && !listed.include?(entry["path"])
						append_document(sections, name, entry["path"], documents.fetch(entry["path"]), entry)
						listed << entry["path"]
					end
					(documents.keys - listed).sort_by{|path| Document.order(path)}.each do |path|
						append_document(sections, name, path, documents.fetch(path))
					end
				end
				sections << "No context files are installed." unless found
				sections.pop while sections.last == ""
				sections.join("\n") + "\n"
			end
			
			private
			
			def load_gem_index(directory)
				path = File.join(directory, "index.yaml")
				metadata = File.file?(path) ? YAML.safe_load_file(path, aliases: false) : {}
				metadata.is_a?(Hash) ? metadata : {}
			rescue Psych::Exception
				{}
			end
			
			def append_document(sections, package, path, document, metadata = {})
				title = metadata["title"] || document.title
				description = metadata["description"] || document.description
				link = URI::DEFAULT_PARSER.escape("#{package}/#{path}", /[^a-zA-Z0-9\-._~\/]/)
				sections.concat(["### [#{escape(title)}](#{link})", ""])
				sections.concat([escape(description), ""]) if description && !description.empty?
			end
			
			def escape(text)
				text.to_s.gsub(/\s+/, " ").gsub(/([\\`*_\[\]<>])/){"\\#{$1}"}
			end
		end
	end
end
