# frozen_string_literal: true

# Released under the MIT License.
# Copyright, 2025-2026, by Samuel Williams.
# Copyright, 2025, by Shopify Inc.

require "fileutils"
require "pathname"
require "yaml"
require "uri"
require "tempfile"
require "rubygems"
require "agent/context/skills/ownership"
require "agent/context/skills/exclusion"
require_relative "paths"
require_relative "document"

module Agent
	module Context
		# Represents the generated index of installed dependency guidance.
		class Index
			# Initialize an index for installed context.
			# @parameter context_path [String] The installed context directory.
			# @parameter specifications [Enumerable] The resolved gems supplying package descriptions.
			def initialize(context_path = CONTEXT_PATH, specifications: ::Gem::Specification)
				@context_path = File.expand_path(context_path)
				@specifications = specifications
			end
			
			# @attribute [String] The installed context directory.
			attr_reader :context_path
			
			# Write the generated index and update local Git exclusions.
			def update_index
				content = generate_index
				
				FileUtils.mkdir_p(@context_path)
				Tempfile.create(".agent-context-index-", @context_path) do |file|
					file.write(content)
					file.flush
					File.rename(file.path, File.join(@context_path, "index.md"))
				end
				
				root = File.dirname(File.dirname(@context_path))
				owners = Skills::Ownership.scan(File.join(root, ".agents", "skills"))
				Skills::Exclusion.prepare(root, owners.keys)&.apply
			end
			
			# Render links relative to the generated index, preserving custom provider metadata.
			# @returns [String] The generated Markdown index.
			def generate_index
				package_descriptions = @specifications.to_h do |specification|
					[specification.name, specification.summary]
				end
				
				sections = [
					"# Context Index",
					"",
					"This index links to guidance installed from resolved gem dependencies. " \
						"It is generated by `bake agent:context:install` and can be refreshed with `bake agent:context:index`.",
					"",
					"Before working on a package, read the relevant context files below. " \
						"If these files are missing, run `bake agent:context:install`.",
					"",
				]
				
				found = false
				provider_names.each do |name|
					directory = File.join(@context_path, name)
					documents = discover_documents(directory)
					next if documents.empty?
					
					metadata = load_gem_index(directory)
					description = metadata["description"] || package_descriptions[name] || "Context files for #{name}"
					sections.concat(["## #{escape(name)}", "", escape(description), ""])
					append_documents(sections, name, documents, metadata)
					found = true
				end
				
				sections << "No context files are installed." unless found
				sections.pop while sections.last == ""
				sections.join("\n") + "\n"
			end
			
			private
			
			def provider_names
				return [] unless Dir.exist?(@context_path)
				
				Dir.children(@context_path).sort.select do |name|
					path = File.join(@context_path, name)
					File.directory?(path) && !File.symlink?(path)
				end
			end
			
			def discover_documents(directory)
				files = Dir.glob(File.join(directory, "**", "*")).select do |path|
					File.file?(path) && !File.symlink?(path) && File.extname(path).downcase == ".md"
				end
				
				# Read root-level skill declarations before excluding their resource directories:
				files.sort_by!{|path| [File.dirname(path) == directory ? 0 : 1, path]}
				
				documents = {}
				skill_roots = []
				files.each do |path|
					relative = Pathname.new(path).relative_path_from(Pathname.new(directory)).to_s
					next if skill_roots.any?{|skill| relative.start_with?("#{skill}/")}
					
					document = Document.load(path)
					if document.skill?
						skill_roots << relative.delete_suffix(File.extname(relative))
					else
						documents[relative] = document
					end
				end
				
				documents
			end
			
			def load_gem_index(directory)
				path = File.join(directory, "index.yaml")
				metadata = File.file?(path) ? YAML.safe_load_file(path, aliases: false) : {}
				metadata.is_a?(Hash) ? metadata : {}
			rescue Psych::Exception
				{}
			end
			
			def append_documents(sections, package, documents, metadata)
				listed = []
				Array(metadata["files"]).each do |entry|
					next unless entry.is_a?(Hash)
					
					path = entry["path"]
					next unless documents.key?(path)
					next if listed.include?(path)
					
					append_document(sections, package, path, documents.fetch(path), entry)
					listed << path
				end
				
				remaining = (documents.keys - listed).sort_by{|path| Document.order(path)}
				remaining.each do |path|
					append_document(sections, package, path, documents.fetch(path))
				end
			end
			
			def append_document(sections, package, path, document, metadata = {})
				title = metadata["title"] || document.title
				description = metadata["description"] || document.description
				link = URI::DEFAULT_PARSER.escape("#{package}/#{path}", /[^a-zA-Z0-9\-._~\/]/)
				
				sections.concat(["### [#{escape(title)}](#{link})", ""])
				sections.concat([escape(description), ""]) if description && !description.empty?
			end
			
			def escape(text)
				text.to_s.gsub(/\s+/, " ").gsub(/([\\`*_\[\]<>])/){"\\#{$1}"}
			end
		end
	end
end
