# frozen_string_literal: true

# Released under the MIT License.
# Copyright, 2026, by Samuel Williams.

require "open3"
require "fileutils"
require "tempfile"
require_relative "ownership"

module Agent
	module Context
		module Skills
			# Represents local Git exclusions shared by context and skill installers.
			class Exclusion
				BEGIN_MARKER = "# BEGIN bake-agent-context"
				END_MARKER = "# END bake-agent-context"
				
				# Prepare exclusions while preserving repository-owned rules.
				# @parameter root [String] The consuming project root.
				# @parameter names [Array(String)] All dependency-owned skills.
				def initialize(root, names)
					output, status = Open3.capture2e("git", "rev-parse", "--show-prefix", "--git-path", "info/exclude", chdir: root)
					return unless status.success?
					prefix, path = output.lines(chomp: true)
					@path = File.expand_path(path, root)
					begin_marker = "#{BEGIN_MARKER} #{prefix}".rstrip
					end_marker = "#{END_MARKER} #{prefix}".rstrip
					pattern = prefix.gsub(/[\\*?\[\]]/){|character| "\\#{character}"}
					@original = File.exist?(@path) ? File.read(@path) : ""
					lines = @original.lines(chomp: true)
					begins = lines.each_index.select{|index| lines[index].strip == begin_marker}
					ends = lines.each_index.select{|index| lines[index].strip == end_marker}
					unless begins.empty? && ends.empty?
						unless begins.length == 1 && ends.length == 1 && begins.first < ends.first
							raise Ownership::Invalid, "Malformed Agent Context exclusion block: #{@path}"
						end
						lines.slice!(begins.first..ends.first)
					end
					lines.pop while lines.last == ""
					lines << "" unless lines.empty?
					lines.concat([
						begin_marker,
						"# Generated by Bake Agent Context; do not edit this block manually.",
						"/#{pattern}.agents/context/",
						*names.sort.map{|name| "/#{pattern}.agents/skills/#{name}/"},
						end_marker,
					])
					@updated = lines.join("\n") + "\n"
				rescue Errno::ENOENT
					# Installation also works when Git is unavailable:
					@path = nil
				end
				
				# Apply the prepared exclusion block.
				def apply
					write(@updated) if @path && @updated != @original
				end
				
				# Restore exclusions if installation fails.
				def restore
					write(@original) if @path && @updated != @original
				end
				
				private
				
				def write(content)
					FileUtils.mkdir_p(File.dirname(@path))
					Tempfile.create(".agent-context-exclude-", File.dirname(@path)) do |file|
						file.write(content)
						file.flush
						File.rename(file.path, @path)
					end
				end
			end
		end
	end
end
